use std::path::PathBuf;

use crate::ServicesExt;
use crate::commands::entity_response::{SkillInfoResponse, SkillListResponse};
use crate::commands::model_config::RequiredNullable;
use meridian_core::agent::skills;
use meridian_core::db::entity::skill::SkillChangeset;
use meridian_core::db::sea::ops::skill as skill_ops;
use meridian_core::db::sea::ops::skill_binding as binding_ops;
use meridian_core::db::sea::ops::skill_binding::{MAX_BINDINGS_PER_ANCHOR, SkillLayer};
use meridian_core::db::types::SqlBool;
use meridian_core::util::now_ms;

#[derive(Debug, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SkillCreateRequest {
    dir_name: String,
    llm_description: String,
    body: String,
    display_name: RequiredNullable<String>,
}

pub fn skills_root(app: &tauri::AppHandle) -> Result<PathBuf, String> {
    let services = app.services();
    let dir = services.paths.skills_root.clone();
    std::fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
    Ok(dir)
}

#[tauri::command]
pub async fn list_skills(app: tauri::AppHandle) -> Result<SkillListResponse, String> {
    let services = app.services();
    skill_ops::list_skills(&services.sea)
        .await
        .map(|rows| rows.into_iter().map(Into::into).collect())
        .map_err(|e| e.to_string())
}

#[tauri::command]
pub async fn rescan_skills(app: tauri::AppHandle) -> Result<SkillListResponse, String> {
    let root = skills_root(&app)?;
    let services = app.services();
    Ok(skills::sync_index(&services.sea, &root)
        .await?
        .into_iter()
        .map(Into::into)
        .collect())
}

#[tauri::command]
pub fn get_skill_body(app: tauri::AppHandle, dir_name: String) -> Result<String, String> {
    let root = skills_root(&app)?;
    skills::read_skill_body(&root, &dir_name).ok_or_else(|| format!("skill '{dir_name}' has no readable SKILL.md"))
}

#[tauri::command]
pub async fn create_skill(app: tauri::AppHandle, request: SkillCreateRequest) -> Result<SkillInfoResponse, String> {
    let root = skills_root(&app)?;
    if root.join(&request.dir_name).exists() {
        return Err(format!("A skill directory named '{}' already exists", request.dir_name));
    }
    // Directory name doubles as the LLM-facing name: one identifier, so the two
    // can never drift apart.
    skills::write_skill_file(
        &root,
        &request.dir_name,
        &request.dir_name,
        &request.llm_description,
        &request.body,
    )?;

    let services = app.services();
    skills::sync_index(&services.sea, &root).await?;

    let dir_name = request.dir_name;
    let display_name = request.display_name.0.filter(|n| !n.trim().is_empty());
    let row = services
        .sea
        .write(async |tx| match display_name {
            Some(name) => skill_ops::update_skill(
                tx,
                &dir_name,
                SkillChangeset {
                    display_name: Some(name),
                    updated_at: Some(now_ms()),
                    ..Default::default()
                },
            )
            .await
            .map(Some),
            None => skill_ops::get_skill(tx, &dir_name).await,
        })
        .await
        .map_err(|e| e.to_string())?;
    row.map(Into::into)
        .ok_or_else(|| format!("skill '{dir_name}' was not indexed after it was written"))
}

#[derive(Debug, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SkillUpdateRequest {
    dir_name: String,
    display_name: Option<String>,
    llm_description: Option<String>,
    body: Option<String>,
    is_enabled: Option<bool>,
}

async fn existing_skill(
    services: &meridian_core::services::Services,
    dir_name: &str,
) -> Result<meridian_core::db::entity::skill::Model, String> {
    skill_ops::get_skill(&services.sea, dir_name)
        .await
        .map_err(|e| e.to_string())?
        .ok_or_else(|| format!("skill '{dir_name}' is not in the index"))
}

#[tauri::command]
pub async fn update_skill(app: tauri::AppHandle, request: SkillUpdateRequest) -> Result<SkillInfoResponse, String> {
    let dir_name = request.dir_name;
    let root = skills_root(&app)?;
    let services = app.services();
    let current = existing_skill(&services, &dir_name).await?;

    if request.llm_description.is_some() || request.body.is_some() {
        if current.is_builtin.get() {
            return Err(format!(
                "'{dir_name}' is generated by Meridian; its contents are rewritten on every launch"
            ));
        }
        let description = request
            .llm_description
            .clone()
            .unwrap_or_else(|| current.llm_description.clone());
        let body = match request.body.clone() {
            Some(b) => b,
            // An unreadable body is an error, not an empty one: defaulting here
            // would rewrite SKILL.md with the description and nothing else.
            None => skills::read_skill_body(&root, &dir_name)
                .ok_or_else(|| format!("skill '{dir_name}' has no readable SKILL.md"))?,
        };
        skills::write_skill_file(&root, &dir_name, &current.llm_name, &description, &body)?;
        skills::sync_index(&services.sea, &root).await?;
    }

    let changeset = SkillChangeset {
        display_name: request.display_name,
        is_enabled: request.is_enabled.map(SqlBool::from),
        updated_at: Some(now_ms()),
        ..Default::default()
    };
    services
        .sea
        .write(async |tx| skill_ops::update_skill(tx, &dir_name, changeset).await)
        .await
        .map(Into::into)
        .map_err(|e| e.to_string())
}

#[tauri::command]
pub async fn delete_skill(app: tauri::AppHandle, dir_name: String) -> Result<(), String> {
    let root = skills_root(&app)?;
    let services = app.services();

    // Enforced here and not only in the UI: the frontend hiding a button is not
    // a guarantee, and a regenerated skill would reappear anyway.
    if existing_skill(&services, &dir_name).await?.is_builtin.get() {
        return Err(format!("'{dir_name}' is a built-in skill and cannot be deleted"));
    }

    skills::delete_skill_dir(&root, &dir_name)?;
    services
        .sea
        .write(async |tx| skill_ops::delete_skill(tx, &dir_name).await)
        .await
        .map(|_| ())
        .map_err(|e| e.to_string())
}

#[derive(Debug, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SkillBindingListRequest {
    pub layer: SkillLayer,
    pub anchor_id: Option<String>,
}

#[derive(Debug, serde::Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct SkillBindingUpdateRequest {
    pub layer: SkillLayer,
    pub anchor_id: Option<String>,
    pub dir_name: String,
    pub bound: bool,
}

pub type SkillBindingNamesResponse = Vec<String>;

#[tauri::command]
pub async fn list_skill_bindings(
    app: tauri::AppHandle,
    request: SkillBindingListRequest,
) -> Result<SkillBindingNamesResponse, String> {
    let services = app.services();
    binding_ops::list_layer(&services.sea, request.layer, request.anchor_id.as_deref())
        .await
        .map_err(|e| e.to_string())
}

#[tauri::command]
pub async fn set_skill_binding(
    app: tauri::AppHandle,
    request: SkillBindingUpdateRequest,
) -> Result<SkillBindingNamesResponse, String> {
    if request.layer != SkillLayer::Global && request.anchor_id.is_none() {
        return Err(format!(
            "binding at the {} layer needs an anchor id",
            request.layer.as_str()
        ));
    }
    let services = app.services();
    let layer = request.layer;
    let anchor = request.anchor_id.as_deref();
    let dir_name = request.dir_name.as_str();

    // The count and the bind share one write lock: checked outside it, two
    // binds racing for the last slot would both see room.
    let refused = services
        .sea
        .write(async |tx| {
            if !request.bound {
                return binding_ops::unbind(tx, layer, anchor, dir_name).await.map(|()| false);
            }
            // Each binding costs context on every request, so the cap is per
            // anchor rather than a global storage limit.
            if binding_ops::count_layer(tx, layer, anchor).await? >= MAX_BINDINGS_PER_ANCHOR {
                return Ok(true);
            }
            binding_ops::bind(tx, layer, anchor, dir_name).await.map(|()| false)
        })
        .await
        .map_err(|e| e.to_string())?;
    if refused {
        return Err(format!(
            "At most {MAX_BINDINGS_PER_ANCHOR} skills can be bound here; each one costs context on every message"
        ));
    }

    binding_ops::list_layer(&services.sea, layer, anchor)
        .await
        .map_err(|e| e.to_string())
}

#[cfg(test)]
mod tests {
    use super::{SkillBindingListRequest, SkillBindingUpdateRequest};
    use meridian_core::db::sea::ops::skill_binding::SkillLayer;

    #[test]
    fn skill_binding_requests_are_strict_and_typed() {
        let list = serde_json::from_value::<SkillBindingListRequest>(serde_json::json!({
            "layer": "project",
            "anchorId": "project-1"
        }))
        .unwrap();
        assert_eq!(list.layer, SkillLayer::Project);
        assert_eq!(list.anchor_id.as_deref(), Some("project-1"));

        assert!(
            serde_json::from_value::<SkillBindingListRequest>(serde_json::json!({
                "layer": "future",
                "anchorId": null
            }))
            .is_err()
        );
        assert!(
            serde_json::from_value::<SkillBindingListRequest>(serde_json::json!({
                "layer": "global",
                "anchorId": null,
                "legacyLayer": "project"
            }))
            .is_err()
        );

        let update = serde_json::from_value::<SkillBindingUpdateRequest>(serde_json::json!({
            "layer": "assistant",
            "anchorId": "assistant-1",
            "dirName": "review",
            "bound": true
        }))
        .unwrap();
        assert_eq!(update.layer, SkillLayer::Assistant);
        assert_eq!(update.anchor_id.as_deref(), Some("assistant-1"));
        assert_eq!(update.dir_name, "review");
        assert!(update.bound);
    }
}
