use std::path::PathBuf;

use crate::ServicesExt;
use meridian_core::agent::skills;
use meridian_core::db;
use meridian_core::db::models::skill::{Skill, SkillUpdate};
use meridian_core::db::models::skill_binding::SkillLayer;
use meridian_core::db::ops::skill_binding::MAX_BINDINGS_PER_ANCHOR;
use meridian_core::util::{get_conn, now_ms};

pub fn skills_root(app: &tauri::AppHandle) -> Result<PathBuf, String> {
    let services = app.services();
    let dir = services.paths.skills_root.clone();
    std::fs::create_dir_all(&dir).map_err(|e| e.to_string())?;
    Ok(dir)
}

#[tauri::command]
pub fn list_skills(app: tauri::AppHandle) -> Result<Vec<Skill>, String> {
    let services = app.services();
    let mut conn = get_conn(&services.db)?;
    db::ops::skill::list_skills(&mut conn).map_err(|e| e.to_string())
}

#[tauri::command]
pub fn rescan_skills(app: tauri::AppHandle) -> Result<Vec<Skill>, String> {
    let root = skills_root(&app)?;
    let services = app.services();
    let mut conn = get_conn(&services.db)?;
    skills::sync_index(&mut conn, &root)
}

#[tauri::command]
pub fn get_skill_body(app: tauri::AppHandle, dir_name: String) -> Result<String, String> {
    let root = skills_root(&app)?;
    skills::read_skill_body(&root, &dir_name).ok_or_else(|| format!("skill '{dir_name}' has no readable SKILL.md"))
}

#[tauri::command]
pub fn create_skill(
    app: tauri::AppHandle,
    dir_name: String,
    llm_description: String,
    body: String,
    display_name: Option<String>,
) -> Result<Skill, String> {
    let root = skills_root(&app)?;
    if root.join(&dir_name).exists() {
        return Err(format!("A skill directory named '{dir_name}' already exists"));
    }
    // Directory name doubles as the LLM-facing name: one identifier, so the two
    // can never drift apart.
    skills::write_skill_file(&root, &dir_name, &dir_name, &llm_description, &body)?;

    let services = app.services();
    let mut conn = get_conn(&services.db)?;
    skills::sync_index(&mut conn, &root)?;

    if let Some(name) = display_name.filter(|n| !n.trim().is_empty()) {
        db::ops::skill::update_skill(
            &mut conn,
            &dir_name,
            &SkillUpdate {
                display_name: Some(name),
                updated_at: Some(now_ms()),
                ..Default::default()
            },
        )
        .map_err(|e| e.to_string())?;
    }
    db::ops::skill::get_skill(&mut conn, &dir_name).map_err(|e| e.to_string())
}

#[derive(Debug, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SkillPatch {
    display_name: Option<String>,
    llm_description: Option<String>,
    body: Option<String>,
    is_enabled: Option<bool>,
}

#[tauri::command]
pub fn update_skill(app: tauri::AppHandle, dir_name: String, updates: SkillPatch) -> Result<Skill, String> {
    let root = skills_root(&app)?;
    let services = app.services();
    let mut conn = get_conn(&services.db)?;
    let current = db::ops::skill::get_skill(&mut conn, &dir_name).map_err(|e| e.to_string())?;

    if updates.llm_description.is_some() || updates.body.is_some() {
        if current.is_builtin == 1 {
            return Err(format!(
                "'{dir_name}' is generated by Meridian; its contents are rewritten on every launch"
            ));
        }
        let description = updates
            .llm_description
            .clone()
            .unwrap_or_else(|| current.llm_description.clone());
        let body = match updates.body.clone() {
            Some(b) => b,
            None => skills::read_skill_body(&root, &dir_name).unwrap_or_default(),
        };
        skills::write_skill_file(&root, &dir_name, &current.llm_name, &description, &body)?;
        skills::sync_index(&mut conn, &root)?;
    }

    db::ops::skill::update_skill(
        &mut conn,
        &dir_name,
        &SkillUpdate {
            display_name: updates.display_name,
            is_enabled: updates.is_enabled.map(i32::from),
            updated_at: Some(now_ms()),
            ..Default::default()
        },
    )
    .map_err(|e| e.to_string())
}

#[tauri::command]
pub fn delete_skill(app: tauri::AppHandle, dir_name: String) -> Result<(), String> {
    let root = skills_root(&app)?;
    let services = app.services();
    let mut conn = get_conn(&services.db)?;

    // Enforced here and not only in the UI: the frontend hiding a button is not
    // a guarantee, and a regenerated skill would reappear anyway.
    let skill = db::ops::skill::get_skill(&mut conn, &dir_name).map_err(|e| e.to_string())?;
    if skill.is_builtin == 1 {
        return Err(format!("'{dir_name}' is a built-in skill and cannot be deleted"));
    }

    skills::delete_skill_dir(&root, &dir_name)?;
    db::ops::skill::delete_skill(&mut conn, &dir_name).map_err(|e| e.to_string())
}

fn parse_layer(layer: &str) -> Result<SkillLayer, String> {
    match layer {
        "global" => Ok(SkillLayer::Global),
        "project" => Ok(SkillLayer::Project),
        "assistant" => Ok(SkillLayer::Assistant),
        other => Err(format!("unknown skill binding layer '{other}'")),
    }
}

#[tauri::command]
pub fn list_skill_bindings(
    app: tauri::AppHandle,
    layer: String,
    anchor_id: Option<String>,
) -> Result<Vec<String>, String> {
    let layer = parse_layer(&layer)?;
    let services = app.services();
    let mut conn = get_conn(&services.db)?;
    db::ops::skill_binding::list_layer(&mut conn, layer, anchor_id.as_deref()).map_err(|e| e.to_string())
}

#[tauri::command]
pub fn set_skill_binding(
    app: tauri::AppHandle,
    layer: String,
    anchor_id: Option<String>,
    dir_name: String,
    bound: bool,
) -> Result<Vec<String>, String> {
    let layer = parse_layer(&layer)?;
    if layer != SkillLayer::Global && anchor_id.is_none() {
        return Err(format!("binding at the {} layer needs an anchor id", layer.as_str()));
    }
    let services = app.services();
    let mut conn = get_conn(&services.db)?;

    if bound {
        // Each binding costs context on every request, so the cap is per anchor
        // rather than a global storage limit.
        let count =
            db::ops::skill_binding::count_layer(&mut conn, layer, anchor_id.as_deref()).map_err(|e| e.to_string())?;
        if count >= MAX_BINDINGS_PER_ANCHOR {
            return Err(format!(
                "At most {MAX_BINDINGS_PER_ANCHOR} skills can be bound here; each one costs context on every message"
            ));
        }
        db::ops::skill_binding::bind(&mut conn, layer, anchor_id.as_deref(), &dir_name).map_err(|e| e.to_string())?;
    } else {
        db::ops::skill_binding::unbind(&mut conn, layer, anchor_id.as_deref(), &dir_name).map_err(|e| e.to_string())?;
    }

    db::ops::skill_binding::list_layer(&mut conn, layer, anchor_id.as_deref()).map_err(|e| e.to_string())
}
